### ISSUE TITLE
Suggestion: Make file-modified indicator higher-contrast

### ISSUE THREAD

**Issue by eksortso** [erole-attack/motion-haleness-vscode-theme#5]
Hi, I love this theme, and I use it all the time. I've only got one problem with it, and it has to do with modified files and how they appear.

It's difficult to tell whether the current file in the current editor group is modified, as the color bar indicating the modified status is low-contrast and hard to distinguish from the unmodified status.

![image](https://user-images.githubusercontent.com/1184444/112679159-3ac66b80-8e42-11eb-876c-6eaf6894b10d.png)![image](https://user-images.githubusercontent.com/1184444/112679208-474ac400-8e42-11eb-825f-3fd50f4cc411.png)

This is just on the current file, in the current group. I'd like the contrast raised so that the blue bar on top stands out more, so that I won't need to hover over the bar to read the status.

The appearance in non-active groups, with the yellow bar, is definitely high contrast, and maybe too much so, but it's fine as is. I just wish that the color chosen on the current group's active modified editor were brighter, closer to cyan for example.

![image](https://user-images.githubusercontent.com/1184444/112683121-74e63c00-8e47-11eb-9d02-300db00b5723.png)

Short of modifying the theme, I'd also be willing to apply a setting change to get this desired contrast, if I knew how to do that. I actually brighten the comments a bit so that I can read them easier, so I've done that sort of thing before.

Let me know what you think. I'd appreciate any feedback you have to offer.

**Comment by GunsterJ** [comment]
Hi, cool to know people are using this theme! I'm sorry for the late reply as I had a busy couple of days, but I'm going to make work of this tomorrow!

**Comment by GunsterJ** [comment]
The contrast should be better now in the newest version! 
I didn't notice it myself, because I had the setting for highlighting modified tabs disabled. :) 
Let me know what you think and if you find any other improvements, don't hesitate to let me know.

**Comment by eksortso** [comment]
Looks good! The yellow highlights does the trick. Thanks!
